version: "3.9"

services:
  ibbi-api:
    container_name: ibbi-api
    build:
      context: .
      args:
        - PORT=${CORE_PORT}
    restart: always
    volumes:
      - ./src:/code/src
    env_file: .env
    ports:
      - ${CORE_PORT}:${CORE_PORT}
    depends_on:
      - postgres-db-ibbi
    networks:
      - api-network

  postgres-db-ibbi:
    container_name: postgres-db-ibbi
    image: postgres
    restart: always
    volumes:
      - ibbi:/var/lib/postgresql/data
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  ibbi: