"""

Revision ID: 0658beca2b2b
Revises: 6e9c31351b8a
Create Date: 2024-06-18 14:46:57.351467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0658beca2b2b'
down_revision: Union[str, None] = '6e9c31351b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('quantity', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchases', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'quantity')
    op.drop_column('purchases', 'product_id')
    # ### end Alembic commands ###
