"""

Revision ID: 872676e35278
Revises: f975d5e23064
Create Date: 2024-06-20 02:15:54.386224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872676e35278'
down_revision: Union[str, None] = 'f975d5e23064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finished_purchases_id'), 'finished_purchases', ['id'], unique=False)
    op.add_column('purchases', sa.Column('finished_purchase_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'finished_purchases', ['finished_purchase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'finished_purchase_id')
    op.drop_index(op.f('ix_finished_purchases_id'), table_name='finished_purchases')
    op.drop_table('finished_purchases')
    # ### end Alembic commands ###
